const NOT_AUTHORIZED = 401;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const INCOMPLETE_PARAMETERS = 400;

module.exports = {
  NOT_AUTHORIZED,
  NOT_FOUND,
  SERVER_ERROR,
  INCOMPLETE_PARAMETERS,
};
